create table message_conversations (
    id bigint generated by default as identity primary key,
    participant_one_id bigint not null references users(id) on delete cascade,
    participant_two_id bigint not null references users(id) on delete cascade,
    last_message_id bigint,
    last_message_at timestamptz,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint ck_message_conversations_pair_order check (participant_one_id < participant_two_id),
    unique (participant_one_id, participant_two_id)
);

create table private_messages (
    id bigint generated by default as identity primary key,
    conversation_id bigint not null references message_conversations(id) on delete cascade,
    sender_id bigint not null references users(id) on delete cascade,
    receiver_id bigint not null references users(id) on delete cascade,
    content text not null,
    is_read boolean not null default false,
    created_at timestamptz not null default now(),
    constraint ck_private_messages_not_self check (sender_id <> receiver_id),
    constraint ck_private_messages_content_not_blank check (length(trim(content)) > 0)
);

alter table message_conversations
    add constraint fk_message_conversations_last_message
    foreign key (last_message_id) references private_messages(id) on delete set null;

create index idx_message_conversations_participant_one on message_conversations(participant_one_id, last_message_at desc, id desc);
create index idx_message_conversations_participant_two on message_conversations(participant_two_id, last_message_at desc, id desc);
create index idx_private_messages_conversation_created on private_messages(conversation_id, created_at desc, id desc);
create index idx_private_messages_receiver_unread on private_messages(receiver_id, is_read, created_at desc);

comment on table message_conversations is '用户私信会话表';
comment on column message_conversations.id is '私信会话主键';
comment on column message_conversations.participant_one_id is '排序后的较小参与者用户主键';
comment on column message_conversations.participant_two_id is '排序后的较大参与者用户主键';
comment on column message_conversations.last_message_id is '最后一条私信主键';
comment on column message_conversations.last_message_at is '最后一条私信发送时间';
comment on column message_conversations.created_at is '创建时间';
comment on column message_conversations.updated_at is '更新时间';

comment on table private_messages is '用户私信消息表';
comment on column private_messages.id is '私信消息主键';
comment on column private_messages.conversation_id is '所属私信会话主键';
comment on column private_messages.sender_id is '发送用户主键';
comment on column private_messages.receiver_id is '接收用户主键';
comment on column private_messages.content is '私信正文';
comment on column private_messages.is_read is '接收方是否已读';
comment on column private_messages.created_at is '创建时间';
