create extension if not exists pgcrypto;
create extension if not exists pg_trgm;
create extension if not exists vector;

create table roles (
    id bigint generated by default as identity primary key,
    code varchar(40) not null unique,
    name varchar(80) not null,
    description text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table users (
    id bigint generated by default as identity primary key,
    username varchar(64) not null unique,
    nickname varchar(80),
    password_hash varchar(255) not null,
    avatar_url text,
    bio text,
    status varchar(20) not null default 'ACTIVE',
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    last_login_at timestamptz,
    constraint ck_users_status check (status in ('ACTIVE', 'DISABLED', 'LOCKED'))
);

create table user_roles (
    user_id bigint not null references users(id) on delete cascade,
    role_id bigint not null references roles(id) on delete cascade,
    created_at timestamptz not null default now(),
    primary key (user_id, role_id)
);

create table user_friendships (
    id bigint generated by default as identity primary key,
    requester_id bigint not null references users(id) on delete cascade,
    addressee_id bigint not null references users(id) on delete cascade,
    status varchar(20) not null default 'PENDING',
    requested_at timestamptz not null default now(),
    accepted_at timestamptz,
    updated_at timestamptz not null default now(),
    constraint ck_user_friendships_status check (status in ('PENDING', 'ACCEPTED', 'REJECTED', 'BLOCKED')),
    constraint ck_user_friendships_not_self check (requester_id <> addressee_id),
    unique (requester_id, addressee_id)
);

create index idx_user_friendships_requester on user_friendships(requester_id, status);
create index idx_user_friendships_addressee on user_friendships(addressee_id, status);

create table categories (
    id bigint generated by default as identity primary key,
    module varchar(30) not null,
    name varchar(80) not null,
    slug varchar(120) not null,
    description text,
    sort_order integer not null default 0,
    enabled boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint ck_categories_module check (module in ('ARTICLE', 'PROJECT', 'INSPIRATION'))
);

create unique index uk_categories_module_slug on categories(module, slug);

create table tags (
    id bigint generated by default as identity primary key,
    name varchar(80) not null,
    slug varchar(120) not null unique,
    color varchar(32),
    weight integer not null default 0,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table articles (
    id bigint generated by default as identity primary key,
    title varchar(200) not null,
    slug varchar(220) not null unique,
    summary text,
    content_markdown text not null default '',
    cover_url text,
    category_id bigint references categories(id) on delete set null,
    status varchar(20) not null default 'DRAFT',
    privacy_type varchar(20) not null default 'PUBLIC',
    view_count bigint not null default 0,
    like_count bigint not null default 0,
    comment_count bigint not null default 0,
    is_top boolean not null default false,
    is_recommend boolean not null default false,
    publish_time timestamptz,
    created_by bigint references users(id) on delete set null,
    updated_by bigint references users(id) on delete set null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint ck_articles_status check (status in ('DRAFT', 'PUBLISHED', 'PRIVATE', 'SCHEDULED', 'ARCHIVED')),
    constraint ck_articles_privacy_type
        check (privacy_type in ('PUBLIC', 'SELF', 'FRIENDS', 'SELECTED_FRIENDS', 'EXCLUDED_FRIENDS'))
);

create index idx_articles_category_id on articles(category_id);
create index idx_articles_publish_time on articles(publish_time desc);
create index idx_articles_title_trgm on articles using gin (title gin_trgm_ops);
create index idx_articles_summary_trgm on articles using gin (summary gin_trgm_ops);
create index idx_articles_content_trgm on articles using gin (content_markdown gin_trgm_ops);

create table article_visibility_users (
    article_id bigint not null references articles(id) on delete cascade,
    user_id bigint not null references users(id) on delete cascade,
    rule_type varchar(20) not null,
    created_at timestamptz not null default now(),
    primary key (article_id, user_id),
    constraint ck_article_visibility_users_rule_type check (rule_type in ('ALLOW', 'DENY'))
);

create index idx_article_visibility_users_user on article_visibility_users(user_id, rule_type);

create table article_versions (
    id bigint generated by default as identity primary key,
    article_id bigint not null references articles(id) on delete cascade,
    version_no integer not null,
    title varchar(200) not null,
    summary text,
    content_markdown text not null,
    created_by bigint references users(id) on delete set null,
    created_at timestamptz not null default now(),
    unique (article_id, version_no)
);

create table article_tags (
    article_id bigint not null references articles(id) on delete cascade,
    tag_id bigint not null references tags(id) on delete cascade,
    primary key (article_id, tag_id)
);

create table portfolio_projects (
    id bigint generated by default as identity primary key,
    title varchar(200) not null,
    slug varchar(220) not null unique,
    description text,
    cover_url text,
    project_type varchar(60) not null,
    tech_stack jsonb not null default '[]'::jsonb,
    github_url text,
    demo_url text,
    video_url text,
    content_markdown text not null default '',
    status varchar(20) not null default 'VISIBLE',
    is_recommend boolean not null default false,
    sort_order integer not null default 0,
    started_at date,
    ended_at date,
    created_by bigint references users(id) on delete set null,
    updated_by bigint references users(id) on delete set null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint ck_portfolio_projects_status check (status in ('VISIBLE', 'HIDDEN', 'DRAFT', 'ARCHIVED'))
);

create index idx_portfolio_projects_title_trgm on portfolio_projects using gin (title gin_trgm_ops);
create index idx_portfolio_projects_description_trgm on portfolio_projects using gin (description gin_trgm_ops);

create table project_tags (
    project_id bigint not null references portfolio_projects(id) on delete cascade,
    tag_id bigint not null references tags(id) on delete cascade,
    primary key (project_id, tag_id)
);

create table project_images (
    id bigint generated by default as identity primary key,
    project_id bigint not null references portfolio_projects(id) on delete cascade,
    image_url text not null,
    caption varchar(200),
    sort_order integer not null default 0,
    created_at timestamptz not null default now()
);

create table inspiration_cards (
    id bigint generated by default as identity primary key,
    title varchar(200) not null,
    content text,
    image_url text,
    card_type varchar(30) not null,
    source_url text,
    color varchar(32),
    is_public boolean not null default true,
    sort_order integer not null default 0,
    created_by bigint references users(id) on delete set null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint ck_inspiration_cards_type check (card_type in ('IMAGE', 'TEXT', 'PROMPT', 'CODE', 'LINK'))
);

create index idx_inspiration_cards_title_trgm on inspiration_cards using gin (title gin_trgm_ops);
create index idx_inspiration_cards_content_trgm on inspiration_cards using gin (content gin_trgm_ops);

create table inspiration_tags (
    inspiration_id bigint not null references inspiration_cards(id) on delete cascade,
    tag_id bigint not null references tags(id) on delete cascade,
    primary key (inspiration_id, tag_id)
);

create table comments (
    id bigint generated by default as identity primary key,
    target_type varchar(30) not null,
    target_id bigint not null,
    parent_id bigint references comments(id) on delete cascade,
    root_id bigint references comments(id) on delete cascade,
    user_id bigint not null references users(id) on delete cascade,
    reply_to_user_id bigint references users(id) on delete set null,
    content text not null,
    status varchar(20) not null default 'PENDING',
    depth integer not null default 0,
    reply_count bigint not null default 0,
    like_count bigint not null default 0,
    ip_address inet,
    user_agent text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint ck_comments_target_type check (target_type in ('ARTICLE', 'PROJECT', 'MESSAGE')),
    constraint ck_comments_status check (status in ('PENDING', 'APPROVED', 'REJECTED', 'SPAM')),
    constraint ck_comments_depth check (depth >= 0)
);

create index idx_comments_target on comments(target_type, target_id);
create index idx_comments_parent_id on comments(parent_id);
create index idx_comments_root_id on comments(root_id);
create index idx_comments_user_id on comments(user_id);
create index idx_comments_status_created_at on comments(status, created_at desc);

create table sensitive_words (
    id bigint generated by default as identity primary key,
    word varchar(120) not null unique,
    match_type varchar(20) not null default 'CONTAINS',
    severity varchar(20) not null default 'REVIEW',
    enabled boolean not null default true,
    created_by bigint references users(id) on delete set null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint ck_sensitive_words_match_type check (match_type in ('EXACT', 'CONTAINS', 'REGEX')),
    constraint ck_sensitive_words_severity check (severity in ('REVIEW', 'REJECT', 'MASK'))
);

create index idx_sensitive_words_enabled on sensitive_words(enabled);

create table theme_configs (
    id bigint generated by default as identity primary key,
    theme_name varchar(80) not null unique,
    display_name varchar(120) not null,
    primary_color varchar(32) not null,
    background_type varchar(40) not null,
    background_image text,
    font_family varchar(120),
    card_style varchar(40) not null,
    layout_type varchar(40) not null,
    is_active boolean not null default false,
    config_json jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create unique index uk_theme_configs_one_active on theme_configs(is_active) where is_active;

create table site_configs (
    id bigint generated by default as identity primary key,
    config_key varchar(120) not null unique,
    config_value jsonb not null,
    description text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table file_resources (
    id bigint generated by default as identity primary key,
    file_name varchar(255) not null,
    original_name varchar(255) not null,
    relative_path text not null,
    public_url text not null,
    file_type varchar(120) not null,
    file_size bigint not null,
    storage_type varchar(30) not null default 'LOCAL',
    module varchar(40) not null,
    created_by bigint references users(id) on delete set null,
    created_at timestamptz not null default now(),
    constraint ck_file_resources_storage_type check (storage_type in ('LOCAL', 'MINIO', 'S3')),
    constraint ck_file_resources_module check (module in ('AVATAR', 'COVER', 'ARTICLE', 'PROJECT', 'INSPIRATION', 'OTHER'))
);

create table file_resource_references (
    id bigint generated by default as identity primary key,
    file_id bigint not null references file_resources(id) on delete cascade,
    target_type varchar(40) not null,
    target_id bigint not null,
    usage_type varchar(40) not null,
    created_at timestamptz not null default now(),
    constraint ck_file_resource_references_target_type
        check (target_type in ('USER', 'ARTICLE', 'PROJECT', 'INSPIRATION', 'COMMENT', 'SITE_CONFIG', 'THEME')),
    constraint ck_file_resource_references_usage_type
        check (usage_type in ('AVATAR', 'COVER', 'CONTENT', 'ATTACHMENT', 'SCREENSHOT', 'CONFIG'))
);

create unique index uk_file_resource_references
    on file_resource_references(file_id, target_type, target_id, usage_type);
create index idx_file_resource_references_target
    on file_resource_references(target_type, target_id);

create table visit_logs (
    id bigint generated by default as identity primary key,
    path text not null,
    target_type varchar(30),
    target_id bigint,
    ip_address inet,
    user_agent text,
    referer text,
    device_type varchar(40),
    browser varchar(80),
    operating_system varchar(80),
    created_at timestamptz not null default now()
);

create index idx_visit_logs_created_at on visit_logs(created_at desc);
create index idx_visit_logs_target on visit_logs(target_type, target_id);

create table like_records (
    id bigint generated by default as identity primary key,
    target_type varchar(30) not null,
    target_id bigint not null,
    user_id bigint not null references users(id) on delete cascade,
    created_at timestamptz not null default now(),
    constraint ck_like_records_target_type check (target_type in ('ARTICLE', 'PROJECT', 'COMMENT', 'INSPIRATION'))
);

create unique index uk_like_records_user_target on like_records(target_type, target_id, user_id);

create table favorite_records (
    id bigint generated by default as identity primary key,
    target_type varchar(30) not null,
    target_id bigint not null,
    user_id bigint not null references users(id) on delete cascade,
    created_at timestamptz not null default now(),
    constraint ck_favorite_records_target_type check (target_type in ('ARTICLE', 'PROJECT', 'INSPIRATION'))
);

create unique index uk_favorite_records_user_target on favorite_records(target_type, target_id, user_id);

create table friend_links (
    id bigint generated by default as identity primary key,
    site_name varchar(120) not null,
    site_url text not null,
    logo_url text,
    description text,
    status varchar(20) not null default 'PENDING',
    sort_order integer not null default 0,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint ck_friend_links_status check (status in ('PENDING', 'APPROVED', 'REJECTED', 'HIDDEN'))
);

create table operation_logs (
    id bigint generated by default as identity primary key,
    operator_id bigint references users(id) on delete set null,
    operation varchar(120) not null,
    module varchar(60) not null,
    target_type varchar(60),
    target_id bigint,
    request_method varchar(20),
    request_path text,
    ip_address inet,
    user_agent text,
    detail_json jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now()
);

create index idx_operation_logs_created_at on operation_logs(created_at desc);
create index idx_operation_logs_operator_id on operation_logs(operator_id);

insert into roles (code, name, description)
values
    ('ADMIN', '管理员', '拥有后台 CMS 和站点配置管理权限'),
    ('USER', '注册用户', '可登录、评论、点赞和收藏公开内容')
on conflict (code) do nothing;

do $$
begin
    if '${adminPasswordHash}' !~ '^\$2[aby]\$[0-9]{2}\$.{53}$' then
        raise exception 'ADMIN_PASSWORD_HASH must be a BCrypt hash';
    end if;
end $$;

insert into users (username, nickname, password_hash, status)
values ('${adminUsername}', '管理员', '${adminPasswordHash}', 'ACTIVE')
on conflict (username) do nothing;

insert into user_roles (user_id, role_id)
select u.id, r.id
from users u
join roles r on r.code = 'ADMIN'
where u.username = '${adminUsername}'
on conflict (user_id, role_id) do nothing;

insert into theme_configs (
    theme_name,
    display_name,
    primary_color,
    background_type,
    font_family,
    card_style,
    layout_type,
    is_active,
    config_json
)
values (
    'glass-space',
    'Glass Space',
    '#7c3aed',
    'star',
    'Inter, system-ui, sans-serif',
    'glass',
    'bento',
    true,
    '{"background": "star", "cardStyle": "glass", "layout": "bento"}'::jsonb
)
on conflict (theme_name) do nothing;
