-- CreatorSpace PostgreSQL 建库初始化片段。
-- Flyway 连接到目标库后执行本迁移，PostgreSQL 不允许在目标库事务内再执行 create database。
-- 首次部署时请先在 postgres 管理库手动执行以下建库语句，再启动后端迁移：
-- create role creatorspace with login password 'change_me';
-- create database creatorspace with owner creatorspace encoding 'UTF8';
-- grant all privileges on database creatorspace to creatorspace;

create extension if not exists pgcrypto;
create extension if not exists pg_trgm;
create extension if not exists vector;

do $$
begin
    execute format(
        'comment on database %I is %L',
        current_database(),
        'CreatorSpace 个人主题博客与创意作品展示平台数据库'
    );
end $$;

comment on schema public is 'CreatorSpace 业务数据 schema';

create table roles (
    id bigint generated by default as identity primary key,
    code varchar(40) not null unique,
    name varchar(80) not null,
    description text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table users (
    id bigint generated by default as identity primary key,
    username varchar(64) not null unique,
    nickname varchar(80),
    password_hash varchar(255) not null,
    avatar_url text,
    bio text,
    status varchar(20) not null default 'ACTIVE',
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    last_login_at timestamptz,
    constraint ck_users_status check (status in ('ACTIVE', 'DISABLED', 'LOCKED'))
);

create table user_roles (
    user_id bigint not null references users(id) on delete cascade,
    role_id bigint not null references roles(id) on delete cascade,
    created_at timestamptz not null default now(),
    primary key (user_id, role_id)
);

create table user_friendships (
    id bigint generated by default as identity primary key,
    requester_id bigint not null references users(id) on delete cascade,
    addressee_id bigint not null references users(id) on delete cascade,
    status varchar(20) not null default 'PENDING',
    requested_at timestamptz not null default now(),
    accepted_at timestamptz,
    updated_at timestamptz not null default now(),
    constraint ck_user_friendships_status check (status in ('PENDING', 'ACCEPTED', 'REJECTED', 'BLOCKED')),
    constraint ck_user_friendships_not_self check (requester_id <> addressee_id),
    unique (requester_id, addressee_id)
);

create index idx_user_friendships_requester on user_friendships(requester_id, status);
create index idx_user_friendships_addressee on user_friendships(addressee_id, status);

create table categories (
    id bigint generated by default as identity primary key,
    module varchar(30) not null,
    name varchar(80) not null,
    slug varchar(120) not null,
    description text,
    sort_order integer not null default 0,
    enabled boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint ck_categories_module check (module in ('ARTICLE', 'PROJECT', 'INSPIRATION'))
);

create unique index uk_categories_module_slug on categories(module, slug);

create table tags (
    id bigint generated by default as identity primary key,
    name varchar(80) not null,
    slug varchar(120) not null unique,
    color varchar(32),
    weight integer not null default 0,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table articles (
    id bigint generated by default as identity primary key,
    title varchar(200) not null,
    slug varchar(220) not null unique,
    summary text,
    content_markdown text not null default '',
    cover_url text,
    category_id bigint references categories(id) on delete set null,
    status varchar(20) not null default 'DRAFT',
    privacy_type varchar(20) not null default 'PUBLIC',
    view_count bigint not null default 0,
    like_count bigint not null default 0,
    comment_count bigint not null default 0,
    is_top boolean not null default false,
    is_recommend boolean not null default false,
    publish_time timestamptz,
    created_by bigint references users(id) on delete set null,
    updated_by bigint references users(id) on delete set null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint ck_articles_status check (status in ('DRAFT', 'PUBLISHED', 'PRIVATE', 'SCHEDULED', 'ARCHIVED')),
    constraint ck_articles_privacy_type
        check (privacy_type in ('PUBLIC', 'SELF', 'FRIENDS', 'SELECTED_FRIENDS', 'EXCLUDED_FRIENDS'))
);

create index idx_articles_category_id on articles(category_id);
create index idx_articles_publish_time on articles(publish_time desc);
create index idx_articles_title_trgm on articles using gin (title gin_trgm_ops);
create index idx_articles_summary_trgm on articles using gin (summary gin_trgm_ops);
create index idx_articles_content_trgm on articles using gin (content_markdown gin_trgm_ops);

create table article_visibility_users (
    article_id bigint not null references articles(id) on delete cascade,
    user_id bigint not null references users(id) on delete cascade,
    rule_type varchar(20) not null,
    created_at timestamptz not null default now(),
    primary key (article_id, user_id),
    constraint ck_article_visibility_users_rule_type check (rule_type in ('ALLOW', 'DENY'))
);

create index idx_article_visibility_users_user on article_visibility_users(user_id, rule_type);

create table article_versions (
    id bigint generated by default as identity primary key,
    article_id bigint not null references articles(id) on delete cascade,
    version_no integer not null,
    title varchar(200) not null,
    summary text,
    content_markdown text not null,
    created_by bigint references users(id) on delete set null,
    created_at timestamptz not null default now(),
    unique (article_id, version_no)
);

create table article_tags (
    article_id bigint not null references articles(id) on delete cascade,
    tag_id bigint not null references tags(id) on delete cascade,
    primary key (article_id, tag_id)
);

create table portfolio_projects (
    id bigint generated by default as identity primary key,
    title varchar(200) not null,
    slug varchar(220) not null unique,
    description text,
    cover_url text,
    project_type varchar(60) not null,
    tech_stack jsonb not null default '[]'::jsonb,
    github_url text,
    demo_url text,
    video_url text,
    content_markdown text not null default '',
    status varchar(20) not null default 'VISIBLE',
    is_recommend boolean not null default false,
    sort_order integer not null default 0,
    started_at date,
    ended_at date,
    created_by bigint references users(id) on delete set null,
    updated_by bigint references users(id) on delete set null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint ck_portfolio_projects_status check (status in ('VISIBLE', 'HIDDEN', 'DRAFT', 'ARCHIVED')),
    constraint ck_portfolio_projects_cover_url_safe check (cover_url is null or cover_url ~* '^(https?://|/uploads/)'),
    constraint ck_portfolio_projects_github_url_safe check (github_url is null or github_url ~* '^https?://'),
    constraint ck_portfolio_projects_demo_url_safe check (demo_url is null or demo_url ~* '^https?://'),
    constraint ck_portfolio_projects_video_url_safe check (video_url is null or video_url ~* '^(https?://|/uploads/)')
);

create index idx_portfolio_projects_title_trgm on portfolio_projects using gin (title gin_trgm_ops);
create index idx_portfolio_projects_description_trgm on portfolio_projects using gin (description gin_trgm_ops);

create table project_tags (
    project_id bigint not null references portfolio_projects(id) on delete cascade,
    tag_id bigint not null references tags(id) on delete cascade,
    primary key (project_id, tag_id)
);

create table project_images (
    id bigint generated by default as identity primary key,
    project_id bigint not null references portfolio_projects(id) on delete cascade,
    image_url text not null,
    caption varchar(200),
    sort_order integer not null default 0,
    created_at timestamptz not null default now()
);

create table inspiration_cards (
    id bigint generated by default as identity primary key,
    title varchar(200) not null,
    content text,
    image_url text,
    card_type varchar(30) not null,
    source_url text,
    color varchar(32),
    is_public boolean not null default true,
    sort_order integer not null default 0,
    created_by bigint references users(id) on delete set null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint ck_inspiration_cards_type check (card_type in ('IMAGE', 'TEXT', 'PROMPT', 'CODE', 'LINK'))
);

create index idx_inspiration_cards_title_trgm on inspiration_cards using gin (title gin_trgm_ops);
create index idx_inspiration_cards_content_trgm on inspiration_cards using gin (content gin_trgm_ops);

create table inspiration_tags (
    inspiration_id bigint not null references inspiration_cards(id) on delete cascade,
    tag_id bigint not null references tags(id) on delete cascade,
    primary key (inspiration_id, tag_id)
);

create table comments (
    id bigint generated by default as identity primary key,
    target_type varchar(30) not null,
    target_id bigint not null,
    parent_id bigint references comments(id) on delete cascade,
    root_id bigint references comments(id) on delete cascade,
    user_id bigint not null references users(id) on delete cascade,
    reply_to_user_id bigint references users(id) on delete set null,
    content text not null,
    status varchar(20) not null default 'PENDING',
    depth integer not null default 0,
    reply_count bigint not null default 0,
    like_count bigint not null default 0,
    ip_address inet,
    user_agent text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint ck_comments_target_type check (target_type in ('ARTICLE', 'PROJECT', 'MESSAGE')),
    constraint ck_comments_status check (status in ('PENDING', 'APPROVED', 'REJECTED', 'SPAM')),
    constraint ck_comments_depth check (depth >= 0)
);

create index idx_comments_target on comments(target_type, target_id);
create index idx_comments_parent_id on comments(parent_id);
create index idx_comments_root_id on comments(root_id);
create index idx_comments_user_id on comments(user_id);
create index idx_comments_status_created_at on comments(status, created_at desc);

create table sensitive_words (
    id bigint generated by default as identity primary key,
    word varchar(120) not null unique,
    match_type varchar(20) not null default 'CONTAINS',
    severity varchar(20) not null default 'REVIEW',
    enabled boolean not null default true,
    created_by bigint references users(id) on delete set null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint ck_sensitive_words_match_type check (match_type in ('EXACT', 'CONTAINS', 'REGEX')),
    constraint ck_sensitive_words_severity check (severity in ('REVIEW', 'REJECT', 'MASK'))
);

create index idx_sensitive_words_enabled on sensitive_words(enabled);

create table theme_configs (
    id bigint generated by default as identity primary key,
    theme_name varchar(80) not null unique,
    display_name varchar(120) not null,
    primary_color varchar(32) not null,
    background_type varchar(40) not null,
    background_image text,
    font_family varchar(120),
    card_style varchar(40) not null,
    layout_type varchar(40) not null,
    is_active boolean not null default false,
    config_json jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create unique index uk_theme_configs_one_active on theme_configs(is_active) where is_active;

create table site_configs (
    id bigint generated by default as identity primary key,
    config_key varchar(120) not null unique,
    config_value jsonb not null,
    description text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table file_resources (
    id bigint generated by default as identity primary key,
    file_name varchar(255) not null,
    original_name varchar(255) not null,
    relative_path text not null,
    public_url text not null,
    file_type varchar(120) not null,
    file_size bigint not null,
    storage_type varchar(30) not null default 'LOCAL',
    module varchar(40) not null,
    created_by bigint references users(id) on delete set null,
    created_at timestamptz not null default now(),
    constraint ck_file_resources_storage_type check (storage_type in ('LOCAL', 'MINIO', 'S3')),
    constraint ck_file_resources_module check (module in ('AVATAR', 'COVER', 'ARTICLE', 'PROJECT', 'INSPIRATION', 'OTHER'))
);

create table file_resource_references (
    id bigint generated by default as identity primary key,
    file_id bigint not null references file_resources(id) on delete cascade,
    target_type varchar(40) not null,
    target_id bigint not null,
    usage_type varchar(40) not null,
    created_at timestamptz not null default now(),
    constraint ck_file_resource_references_target_type
        check (target_type in ('USER', 'ARTICLE', 'PROJECT', 'INSPIRATION', 'COMMENT', 'SITE_CONFIG', 'THEME')),
    constraint ck_file_resource_references_usage_type
        check (usage_type in ('AVATAR', 'COVER', 'CONTENT', 'ATTACHMENT', 'SCREENSHOT', 'CONFIG'))
);

create unique index uk_file_resource_references
    on file_resource_references(file_id, target_type, target_id, usage_type);
create index idx_file_resource_references_target
    on file_resource_references(target_type, target_id);

create table visit_logs (
    id bigint generated by default as identity primary key,
    path text not null,
    target_type varchar(30),
    target_id bigint,
    ip_address inet,
    user_agent text,
    referer text,
    device_type varchar(40),
    browser varchar(80),
    operating_system varchar(80),
    created_at timestamptz not null default now()
);

create index idx_visit_logs_created_at on visit_logs(created_at desc);
create index idx_visit_logs_target on visit_logs(target_type, target_id);

create table like_records (
    id bigint generated by default as identity primary key,
    target_type varchar(30) not null,
    target_id bigint not null,
    user_id bigint not null references users(id) on delete cascade,
    created_at timestamptz not null default now(),
    constraint ck_like_records_target_type check (target_type in ('ARTICLE', 'PROJECT', 'COMMENT', 'INSPIRATION'))
);

create unique index uk_like_records_user_target on like_records(target_type, target_id, user_id);

create table favorite_records (
    id bigint generated by default as identity primary key,
    target_type varchar(30) not null,
    target_id bigint not null,
    user_id bigint not null references users(id) on delete cascade,
    created_at timestamptz not null default now(),
    constraint ck_favorite_records_target_type check (target_type in ('ARTICLE', 'PROJECT', 'INSPIRATION'))
);

create unique index uk_favorite_records_user_target on favorite_records(target_type, target_id, user_id);

create table friend_links (
    id bigint generated by default as identity primary key,
    site_name varchar(120) not null,
    site_url text not null,
    logo_url text,
    description text,
    status varchar(20) not null default 'PENDING',
    sort_order integer not null default 0,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint ck_friend_links_status check (status in ('PENDING', 'APPROVED', 'REJECTED', 'HIDDEN'))
);

create table operation_logs (
    id bigint generated by default as identity primary key,
    operator_id bigint references users(id) on delete set null,
    operation varchar(120) not null,
    module varchar(60) not null,
    target_type varchar(60),
    target_id bigint,
    request_method varchar(20),
    request_path text,
    ip_address inet,
    user_agent text,
    detail_json jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now()
);

create index idx_operation_logs_created_at on operation_logs(created_at desc);
create index idx_operation_logs_operator_id on operation_logs(operator_id);

create table user_profiles (
    user_id bigint primary key references users(id) on delete cascade,
    display_name varchar(120) not null,
    headline varchar(180),
    location varchar(120),
    website_url text,
    profile_json jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table site_profiles (
    id bigint generated by default as identity primary key,
    profile_key varchar(80) not null unique,
    display_name varchar(120) not null,
    headline varchar(180),
    avatar_url text,
    bio text,
    contact_email varchar(180),
    location varchar(120),
    profile_json jsonb not null default '{}'::jsonb,
    is_active boolean not null default false,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create unique index uk_site_profiles_one_active on site_profiles(is_active) where is_active;

create table navigation_items (
    id bigint generated by default as identity primary key,
    label varchar(80) not null,
    path varchar(180) not null,
    icon varchar(80),
    group_name varchar(80) not null default 'primary',
    sort_order integer not null default 0,
    visible boolean not null default true,
    extra_json jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create index idx_navigation_items_visible_sort on navigation_items(visible, sort_order);

create table social_links (
    id bigint generated by default as identity primary key,
    platform varchar(80) not null,
    label varchar(120) not null,
    url text not null,
    icon varchar(80),
    sort_order integer not null default 0,
    visible boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table page_configs (
    id bigint generated by default as identity primary key,
    page_key varchar(120) not null unique,
    title varchar(180) not null,
    slug varchar(180) not null unique,
    seo_title varchar(180),
    seo_description text,
    content_json jsonb not null default '{}'::jsonb,
    layout_json jsonb not null default '{}'::jsonb,
    status varchar(20) not null default 'PUBLISHED',
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint ck_page_configs_status check (status in ('DRAFT', 'PUBLISHED', 'ARCHIVED'))
);

create table theme_variants (
    id bigint generated by default as identity primary key,
    theme_id bigint not null references theme_configs(id) on delete cascade,
    variant_name varchar(100) not null,
    density varchar(40) not null default 'comfortable',
    color_tokens jsonb not null default '{}'::jsonb,
    font_tokens jsonb not null default '{}'::jsonb,
    motion_tokens jsonb not null default '{}'::jsonb,
    card_tokens jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (theme_id, variant_name)
);

create table theme_assets (
    id bigint generated by default as identity primary key,
    theme_id bigint not null references theme_configs(id) on delete cascade,
    file_id bigint references file_resources(id) on delete set null,
    asset_type varchar(40) not null,
    asset_url text,
    sort_order integer not null default 0,
    created_at timestamptz not null default now(),
    constraint ck_theme_assets_type check (asset_type in ('BACKGROUND', 'CURSOR', 'COVER_RULE', 'NOISE', 'OTHER'))
);

create table theme_versions (
    id bigint generated by default as identity primary key,
    theme_id bigint not null references theme_configs(id) on delete cascade,
    version_no integer not null,
    snapshot_json jsonb not null,
    created_by bigint references users(id) on delete set null,
    created_at timestamptz not null default now(),
    unique (theme_id, version_no)
);

create table tag_aliases (
    id bigint generated by default as identity primary key,
    tag_id bigint not null references tags(id) on delete cascade,
    alias varchar(120) not null,
    created_at timestamptz not null default now(),
    unique (tag_id, alias)
);

create table article_series (
    id bigint generated by default as identity primary key,
    title varchar(180) not null,
    slug varchar(200) not null unique,
    description text,
    cover_url text,
    sort_order integer not null default 0,
    status varchar(20) not null default 'ACTIVE',
    created_by bigint references users(id) on delete set null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint ck_article_series_status check (status in ('ACTIVE', 'HIDDEN', 'ARCHIVED'))
);

create table article_series_items (
    series_id bigint not null references article_series(id) on delete cascade,
    article_id bigint not null references articles(id) on delete cascade,
    sort_order integer not null default 0,
    note text,
    created_at timestamptz not null default now(),
    primary key (series_id, article_id)
);

create table article_relations (
    id bigint generated by default as identity primary key,
    source_article_id bigint not null references articles(id) on delete cascade,
    target_article_id bigint not null references articles(id) on delete cascade,
    relation_type varchar(40) not null,
    sort_order integer not null default 0,
    created_at timestamptz not null default now(),
    constraint ck_article_relations_type check (relation_type in ('NEXT_READ', 'RELATED', 'PREREQUISITE', 'FOLLOW_UP')),
    constraint ck_article_relations_not_self check (source_article_id <> target_article_id),
    unique (source_article_id, target_article_id, relation_type)
);

create table project_milestones (
    id bigint generated by default as identity primary key,
    project_id bigint not null references portfolio_projects(id) on delete cascade,
    title varchar(160) not null,
    description text,
    milestone_date date,
    sort_order integer not null default 0,
    created_at timestamptz not null default now()
);

create table project_links (
    id bigint generated by default as identity primary key,
    project_id bigint not null references portfolio_projects(id) on delete cascade,
    link_type varchar(40) not null,
    label varchar(120) not null,
    url text not null,
    safe_status varchar(20) not null default 'PENDING',
    sort_order integer not null default 0,
    created_at timestamptz not null default now(),
    constraint ck_project_links_type check (link_type in ('GITHUB', 'DEMO', 'VIDEO', 'DOC', 'ARTICLE', 'OTHER')),
    constraint ck_project_links_safe_status check (safe_status in ('PENDING', 'SAFE', 'BLOCKED')),
    constraint ck_project_links_url_safe check (url ~* '^https?://')
);

create table project_process_notes (
    id bigint generated by default as identity primary key,
    project_id bigint not null references portfolio_projects(id) on delete cascade,
    phase varchar(80) not null,
    title varchar(160) not null,
    body text not null,
    sort_order integer not null default 0,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table inspiration_sources (
    id bigint generated by default as identity primary key,
    inspiration_id bigint not null references inspiration_cards(id) on delete cascade,
    source_type varchar(40) not null,
    title varchar(180),
    url text,
    author varchar(120),
    captured_at timestamptz,
    created_at timestamptz not null default now(),
    constraint ck_inspiration_sources_type check (source_type in ('URL', 'BOOK', 'IMAGE', 'QUOTE', 'PROMPT', 'OTHER'))
);

create table inspiration_relations (
    id bigint generated by default as identity primary key,
    inspiration_id bigint not null references inspiration_cards(id) on delete cascade,
    target_type varchar(40) not null,
    target_id bigint not null,
    relation_type varchar(40) not null default 'REFERENCE',
    created_at timestamptz not null default now(),
    constraint ck_inspiration_relations_target_type check (target_type in ('ARTICLE', 'PROJECT', 'INSPIRATION')),
    constraint ck_inspiration_relations_type check (relation_type in ('REFERENCE', 'SEED', 'DERIVED_FROM'))
);

create table content_blocks (
    id bigint generated by default as identity primary key,
    owner_type varchar(40) not null,
    owner_id bigint,
    block_key varchar(120) not null,
    block_type varchar(40) not null,
    title varchar(180),
    body text,
    config_json jsonb not null default '{}'::jsonb,
    sort_order integer not null default 0,
    visible boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint ck_content_blocks_owner_type check (owner_type in ('HOME', 'ABOUT', 'ARTICLE', 'PROJECT', 'INSPIRATION', 'THEME')),
    constraint ck_content_blocks_type check (block_type in ('HERO', 'TEXT', 'GALLERY', 'CTA', 'STAT', 'TIMELINE', 'MARKDOWN', 'CUSTOM'))
);

create index idx_content_blocks_owner on content_blocks(owner_type, owner_id, visible, sort_order);

create table content_block_assets (
    block_id bigint not null references content_blocks(id) on delete cascade,
    file_id bigint not null references file_resources(id) on delete cascade,
    usage_type varchar(40) not null default 'CONTENT',
    sort_order integer not null default 0,
    created_at timestamptz not null default now(),
    primary key (block_id, file_id, usage_type)
);

create table comment_reactions (
    id bigint generated by default as identity primary key,
    comment_id bigint not null references comments(id) on delete cascade,
    user_id bigint not null references users(id) on delete cascade,
    reaction_type varchar(40) not null default 'LIKE',
    created_at timestamptz not null default now(),
    constraint ck_comment_reactions_type check (reaction_type in ('LIKE', 'THANKS', 'INSIGHTFUL')),
    unique (comment_id, user_id, reaction_type)
);

create table guestbook_entries (
    id bigint generated by default as identity primary key,
    user_id bigint references users(id) on delete set null,
    display_name varchar(120) not null,
    content text not null,
    status varchar(20) not null default 'PENDING',
    like_count bigint not null default 0,
    ip_address inet,
    user_agent text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint ck_guestbook_entries_status check (status in ('PENDING', 'APPROVED', 'REJECTED', 'SPAM'))
);

create index idx_guestbook_entries_status_created on guestbook_entries(status, created_at desc);

create table content_statistics (
    id bigint generated by default as identity primary key,
    target_type varchar(40) not null,
    target_id bigint not null,
    view_count bigint not null default 0,
    like_count bigint not null default 0,
    favorite_count bigint not null default 0,
    comment_count bigint not null default 0,
    last_viewed_at timestamptz,
    updated_at timestamptz not null default now(),
    constraint ck_content_statistics_target_type check (target_type in ('ARTICLE', 'PROJECT', 'INSPIRATION', 'PAGE')),
    unique (target_type, target_id)
);

create table search_logs (
    id bigint generated by default as identity primary key,
    keyword varchar(200) not null,
    result_count integer not null default 0,
    user_id bigint references users(id) on delete set null,
    ip_address inet,
    user_agent text,
    created_at timestamptz not null default now()
);

create index idx_search_logs_keyword_trgm on search_logs using gin (keyword gin_trgm_ops);
create index idx_search_logs_created_at on search_logs(created_at desc);

create table daily_metrics (
    metric_date date not null,
    metric_key varchar(80) not null,
    metric_value bigint not null default 0,
    detail_json jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    primary key (metric_date, metric_key)
);

create table admin_audit_snapshots (
    id bigint generated by default as identity primary key,
    target_type varchar(60) not null,
    target_id bigint not null,
    snapshot_json jsonb not null,
    created_by bigint references users(id) on delete set null,
    created_at timestamptz not null default now()
);

create index idx_admin_audit_snapshots_target on admin_audit_snapshots(target_type, target_id, created_at desc);

create table ai_agent_tasks (
    id bigint generated by default as identity primary key,
    task_type varchar(60) not null,
    target_type varchar(60),
    target_id bigint,
    prompt text not null,
    status varchar(20) not null default 'PENDING',
    provider varchar(40) not null default 'zhipu',
    model_name varchar(120),
    created_by bigint references users(id) on delete set null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint ck_ai_agent_tasks_status check (status in ('PENDING', 'RUNNING', 'SUCCEEDED', 'FAILED', 'DISCARDED'))
);

create table ai_agent_messages (
    id bigint generated by default as identity primary key,
    task_id bigint not null references ai_agent_tasks(id) on delete cascade,
    role varchar(30) not null,
    content text not null,
    token_count integer,
    created_at timestamptz not null default now(),
    constraint ck_ai_agent_messages_role check (role in ('SYSTEM', 'USER', 'ASSISTANT', 'TOOL'))
);

create table ai_suggestions (
    id bigint generated by default as identity primary key,
    task_id bigint references ai_agent_tasks(id) on delete set null,
    target_type varchar(60),
    target_id bigint,
    suggestion_type varchar(60) not null,
    content text not null,
    status varchar(20) not null default 'PENDING',
    adopted_by bigint references users(id) on delete set null,
    adopted_at timestamptz,
    created_at timestamptz not null default now(),
    constraint ck_ai_suggestions_status check (status in ('PENDING', 'ADOPTED', 'REJECTED', 'EXPIRED'))
);

comment on table roles is '系统角色表';
comment on column roles.id is '角色主键';
comment on column roles.code is '角色编码';
comment on column roles.name is '角色名称';
comment on column roles.description is '角色说明';
comment on column roles.created_at is '创建时间';
comment on column roles.updated_at is '更新时间';

comment on table users is '用户和创作者基础信息表';
comment on column users.id is '用户主键';
comment on column users.username is '登录用户名';
comment on column users.nickname is '公开昵称';
comment on column users.password_hash is 'BCrypt 密码哈希';
comment on column users.avatar_url is '头像访问地址';
comment on column users.bio is '个人简介';
comment on column users.status is '账号状态';
comment on column users.created_at is '创建时间';
comment on column users.updated_at is '更新时间';
comment on column users.last_login_at is '最后登录时间';

comment on table user_roles is '用户角色关联表';
comment on column user_roles.user_id is '用户主键';
comment on column user_roles.role_id is '角色主键';
comment on column user_roles.created_at is '授权时间';

comment on table user_friendships is '用户好友关系表';
comment on column user_friendships.id is '好友关系主键';
comment on column user_friendships.requester_id is '发起用户主键';
comment on column user_friendships.addressee_id is '接收用户主键';
comment on column user_friendships.status is '好友关系状态';
comment on column user_friendships.requested_at is '申请时间';
comment on column user_friendships.accepted_at is '通过时间';
comment on column user_friendships.updated_at is '更新时间';

comment on table categories is '内容分类表';
comment on column categories.id is '分类主键';
comment on column categories.module is '所属内容模块';
comment on column categories.name is '分类名称';
comment on column categories.slug is '分类 URL 标识';
comment on column categories.description is '分类说明';
comment on column categories.sort_order is '排序值';
comment on column categories.enabled is '是否启用';
comment on column categories.created_at is '创建时间';
comment on column categories.updated_at is '更新时间';

comment on table tags is '内容标签表';
comment on column tags.id is '标签主键';
comment on column tags.name is '标签名称';
comment on column tags.slug is '标签 URL 标识';
comment on column tags.color is '标签展示色';
comment on column tags.weight is '标签权重';
comment on column tags.created_at is '创建时间';
comment on column tags.updated_at is '更新时间';

comment on table articles is '文章内容表';
comment on column articles.id is '文章主键';
comment on column articles.title is '文章标题';
comment on column articles.slug is '文章 URL 标识';
comment on column articles.summary is '文章摘要';
comment on column articles.content_markdown is 'Markdown 正文';
comment on column articles.cover_url is '文章封面地址';
comment on column articles.category_id is '所属分类主键';
comment on column articles.status is '内容状态';
comment on column articles.privacy_type is '隐私可见性类型';
comment on column articles.view_count is '阅读次数';
comment on column articles.like_count is '点赞次数';
comment on column articles.comment_count is '评论次数';
comment on column articles.is_top is '是否置顶';
comment on column articles.is_recommend is '是否推荐';
comment on column articles.publish_time is '发布时间';
comment on column articles.created_by is '创建用户主键';
comment on column articles.updated_by is '更新用户主键';
comment on column articles.created_at is '创建时间';
comment on column articles.updated_at is '更新时间';

comment on table article_visibility_users is '文章指定用户可见规则表';
comment on column article_visibility_users.article_id is '文章主键';
comment on column article_visibility_users.user_id is '用户主键';
comment on column article_visibility_users.rule_type is '可见规则类型';
comment on column article_visibility_users.created_at is '创建时间';

comment on table article_versions is '文章历史版本表';
comment on column article_versions.id is '文章版本主键';
comment on column article_versions.article_id is '文章主键';
comment on column article_versions.version_no is '版本号';
comment on column article_versions.title is '版本标题';
comment on column article_versions.summary is '版本摘要';
comment on column article_versions.content_markdown is '版本 Markdown 正文';
comment on column article_versions.created_by is '创建用户主键';
comment on column article_versions.created_at is '创建时间';

comment on table article_tags is '文章标签关联表';
comment on column article_tags.article_id is '文章主键';
comment on column article_tags.tag_id is '标签主键';

comment on table portfolio_projects is '作品展示表';
comment on column portfolio_projects.id is '作品主键';
comment on column portfolio_projects.title is '作品标题';
comment on column portfolio_projects.slug is '作品 URL 标识';
comment on column portfolio_projects.description is '作品简介';
comment on column portfolio_projects.cover_url is '作品封面地址';
comment on column portfolio_projects.project_type is '作品类型';
comment on column portfolio_projects.tech_stack is '技术栈 JSON 列表';
comment on column portfolio_projects.github_url is 'GitHub 仓库地址';
comment on column portfolio_projects.demo_url is '在线演示地址';
comment on column portfolio_projects.video_url is '视频展示地址';
comment on column portfolio_projects.content_markdown is '作品 Markdown 详情';
comment on column portfolio_projects.status is '作品状态';
comment on column portfolio_projects.is_recommend is '是否推荐';
comment on column portfolio_projects.sort_order is '排序值';
comment on column portfolio_projects.started_at is '开始日期';
comment on column portfolio_projects.ended_at is '结束日期';
comment on column portfolio_projects.created_by is '创建用户主键';
comment on column portfolio_projects.updated_by is '更新用户主键';
comment on column portfolio_projects.created_at is '创建时间';
comment on column portfolio_projects.updated_at is '更新时间';

comment on table project_tags is '作品标签关联表';
comment on column project_tags.project_id is '作品主键';
comment on column project_tags.tag_id is '标签主键';

comment on table project_images is '作品图片表';
comment on column project_images.id is '作品图片主键';
comment on column project_images.project_id is '作品主键';
comment on column project_images.image_url is '图片访问地址';
comment on column project_images.caption is '图片说明';
comment on column project_images.sort_order is '排序值';
comment on column project_images.created_at is '创建时间';

comment on table inspiration_cards is '灵感卡片表';
comment on column inspiration_cards.id is '灵感卡片主键';
comment on column inspiration_cards.title is '灵感标题';
comment on column inspiration_cards.content is '灵感内容';
comment on column inspiration_cards.image_url is '灵感图片地址';
comment on column inspiration_cards.card_type is '卡片类型';
comment on column inspiration_cards.source_url is '来源地址';
comment on column inspiration_cards.color is '展示色';
comment on column inspiration_cards.is_public is '是否公开展示';
comment on column inspiration_cards.sort_order is '排序值';
comment on column inspiration_cards.created_by is '创建用户主键';
comment on column inspiration_cards.created_at is '创建时间';
comment on column inspiration_cards.updated_at is '更新时间';

comment on table inspiration_tags is '灵感标签关联表';
comment on column inspiration_tags.inspiration_id is '灵感卡片主键';
comment on column inspiration_tags.tag_id is '标签主键';

comment on table comments is '评论表';
comment on column comments.id is '评论主键';
comment on column comments.target_type is '评论目标类型';
comment on column comments.target_id is '评论目标主键';
comment on column comments.parent_id is '父评论主键';
comment on column comments.root_id is '根评论主键';
comment on column comments.user_id is '评论用户主键';
comment on column comments.reply_to_user_id is '被回复用户主键';
comment on column comments.content is '评论内容';
comment on column comments.status is '审核状态';
comment on column comments.depth is '评论层级深度';
comment on column comments.reply_count is '回复数量';
comment on column comments.like_count is '点赞数量';
comment on column comments.ip_address is '评论 IP 地址';
comment on column comments.user_agent is '客户端 User-Agent';
comment on column comments.created_at is '创建时间';
comment on column comments.updated_at is '更新时间';

comment on table sensitive_words is '敏感词规则表';
comment on column sensitive_words.id is '敏感词主键';
comment on column sensitive_words.word is '敏感词内容';
comment on column sensitive_words.match_type is '匹配方式';
comment on column sensitive_words.severity is '处理级别';
comment on column sensitive_words.enabled is '是否启用';
comment on column sensitive_words.created_by is '创建用户主键';
comment on column sensitive_words.created_at is '创建时间';
comment on column sensitive_words.updated_at is '更新时间';

comment on table theme_configs is '站点主题配置表';
comment on column theme_configs.id is '主题配置主键';
comment on column theme_configs.theme_name is '主题内部名称';
comment on column theme_configs.display_name is '主题展示名称';
comment on column theme_configs.primary_color is '主题主色';
comment on column theme_configs.background_type is '背景类型';
comment on column theme_configs.background_image is '背景图片地址';
comment on column theme_configs.font_family is '字体族配置';
comment on column theme_configs.card_style is '卡片样式';
comment on column theme_configs.layout_type is '布局类型';
comment on column theme_configs.is_active is '是否当前启用主题';
comment on column theme_configs.config_json is '主题扩展配置 JSON';
comment on column theme_configs.created_at is '创建时间';
comment on column theme_configs.updated_at is '更新时间';

comment on table site_configs is '站点配置表';
comment on column site_configs.id is '站点配置主键';
comment on column site_configs.config_key is '配置键';
comment on column site_configs.config_value is '配置值 JSON';
comment on column site_configs.description is '配置说明';
comment on column site_configs.created_at is '创建时间';
comment on column site_configs.updated_at is '更新时间';

comment on table file_resources is '文件资源表';
comment on column file_resources.id is '文件资源主键';
comment on column file_resources.file_name is '存储文件名';
comment on column file_resources.original_name is '原始文件名';
comment on column file_resources.relative_path is '相对存储路径';
comment on column file_resources.public_url is '公开访问地址';
comment on column file_resources.file_type is '文件 MIME 类型';
comment on column file_resources.file_size is '文件大小字节数';
comment on column file_resources.storage_type is '存储类型';
comment on column file_resources.module is '所属业务模块';
comment on column file_resources.created_by is '上传用户主键';
comment on column file_resources.created_at is '创建时间';

comment on table file_resource_references is '文件资源引用表';
comment on column file_resource_references.id is '文件引用主键';
comment on column file_resource_references.file_id is '文件资源主键';
comment on column file_resource_references.target_type is '引用目标类型';
comment on column file_resource_references.target_id is '引用目标主键';
comment on column file_resource_references.usage_type is '文件用途类型';
comment on column file_resource_references.created_at is '创建时间';

comment on table visit_logs is '访问日志表';
comment on column visit_logs.id is '访问日志主键';
comment on column visit_logs.path is '访问路径';
comment on column visit_logs.target_type is '访问目标类型';
comment on column visit_logs.target_id is '访问目标主键';
comment on column visit_logs.ip_address is '访问 IP 地址';
comment on column visit_logs.user_agent is '客户端 User-Agent';
comment on column visit_logs.referer is '来源页面';
comment on column visit_logs.device_type is '设备类型';
comment on column visit_logs.browser is '浏览器名称';
comment on column visit_logs.operating_system is '操作系统名称';
comment on column visit_logs.created_at is '创建时间';

comment on table like_records is '点赞记录表';
comment on column like_records.id is '点赞记录主键';
comment on column like_records.target_type is '点赞目标类型';
comment on column like_records.target_id is '点赞目标主键';
comment on column like_records.user_id is '点赞用户主键';
comment on column like_records.created_at is '创建时间';

comment on table favorite_records is '收藏记录表';
comment on column favorite_records.id is '收藏记录主键';
comment on column favorite_records.target_type is '收藏目标类型';
comment on column favorite_records.target_id is '收藏目标主键';
comment on column favorite_records.user_id is '收藏用户主键';
comment on column favorite_records.created_at is '创建时间';

comment on table friend_links is '友情链接表';
comment on column friend_links.id is '友情链接主键';
comment on column friend_links.site_name is '站点名称';
comment on column friend_links.site_url is '站点地址';
comment on column friend_links.logo_url is '站点 Logo 地址';
comment on column friend_links.description is '站点说明';
comment on column friend_links.status is '审核状态';
comment on column friend_links.sort_order is '排序值';
comment on column friend_links.created_at is '创建时间';
comment on column friend_links.updated_at is '更新时间';

comment on table operation_logs is '后台操作日志表';
comment on column operation_logs.id is '操作日志主键';
comment on column operation_logs.operator_id is '操作人用户主键';
comment on column operation_logs.operation is '操作名称';
comment on column operation_logs.module is '业务模块';
comment on column operation_logs.target_type is '操作目标类型';
comment on column operation_logs.target_id is '操作目标主键';
comment on column operation_logs.request_method is '请求方法';
comment on column operation_logs.request_path is '请求路径';
comment on column operation_logs.ip_address is '操作 IP 地址';
comment on column operation_logs.user_agent is '客户端 User-Agent';
comment on column operation_logs.detail_json is '操作详情 JSON';
comment on column operation_logs.created_at is '创建时间';

comment on table user_profiles is '用户公开资料表';
comment on column user_profiles.user_id is '用户主键';
comment on column user_profiles.display_name is '展示名称';
comment on column user_profiles.headline is '个人标题';
comment on column user_profiles.location is '所在地';
comment on column user_profiles.website_url is '个人网站地址';
comment on column user_profiles.profile_json is '资料扩展 JSON';
comment on column user_profiles.created_at is '创建时间';
comment on column user_profiles.updated_at is '更新时间';

comment on table site_profiles is '站点主人资料表';
comment on column site_profiles.id is '站点资料主键';
comment on column site_profiles.profile_key is '站点资料键';
comment on column site_profiles.display_name is '展示名称';
comment on column site_profiles.headline is '一句话介绍';
comment on column site_profiles.avatar_url is '头像地址';
comment on column site_profiles.bio is '个人介绍';
comment on column site_profiles.contact_email is '联系邮箱';
comment on column site_profiles.location is '所在地';
comment on column site_profiles.profile_json is '站点资料扩展 JSON';
comment on column site_profiles.is_active is '是否当前启用';
comment on column site_profiles.created_at is '创建时间';
comment on column site_profiles.updated_at is '更新时间';

comment on table navigation_items is '站点导航配置表';
comment on column navigation_items.id is '导航主键';
comment on column navigation_items.label is '导航显示文本';
comment on column navigation_items.path is '导航路径';
comment on column navigation_items.icon is '导航图标';
comment on column navigation_items.group_name is '导航分组';
comment on column navigation_items.sort_order is '排序值';
comment on column navigation_items.visible is '是否显示';
comment on column navigation_items.extra_json is '导航扩展 JSON';
comment on column navigation_items.created_at is '创建时间';
comment on column navigation_items.updated_at is '更新时间';

comment on table social_links is '社交链接表';
comment on column social_links.id is '社交链接主键';
comment on column social_links.platform is '平台名称';
comment on column social_links.label is '展示文本';
comment on column social_links.url is '链接地址';
comment on column social_links.icon is '平台图标';
comment on column social_links.sort_order is '排序值';
comment on column social_links.visible is '是否显示';
comment on column social_links.created_at is '创建时间';
comment on column social_links.updated_at is '更新时间';

comment on table page_configs is '页面配置表';
comment on column page_configs.id is '页面配置主键';
comment on column page_configs.page_key is '页面配置键';
comment on column page_configs.title is '页面标题';
comment on column page_configs.slug is '页面 URL 标识';
comment on column page_configs.seo_title is 'SEO 标题';
comment on column page_configs.seo_description is 'SEO 描述';
comment on column page_configs.content_json is '页面内容 JSON';
comment on column page_configs.layout_json is '页面布局 JSON';
comment on column page_configs.status is '页面状态';
comment on column page_configs.created_at is '创建时间';
comment on column page_configs.updated_at is '更新时间';

comment on table theme_variants is '主题变量方案表';
comment on column theme_variants.id is '主题变量主键';
comment on column theme_variants.theme_id is '主题配置主键';
comment on column theme_variants.variant_name is '变量方案名称';
comment on column theme_variants.density is '布局密度';
comment on column theme_variants.color_tokens is '颜色 token JSON';
comment on column theme_variants.font_tokens is '字体 token JSON';
comment on column theme_variants.motion_tokens is '动效 token JSON';
comment on column theme_variants.card_tokens is '卡片 token JSON';
comment on column theme_variants.created_at is '创建时间';
comment on column theme_variants.updated_at is '更新时间';

comment on table theme_assets is '主题资源表';
comment on column theme_assets.id is '主题资源主键';
comment on column theme_assets.theme_id is '主题配置主键';
comment on column theme_assets.file_id is '文件资源主键';
comment on column theme_assets.asset_type is '资源类型';
comment on column theme_assets.asset_url is '资源访问地址';
comment on column theme_assets.sort_order is '排序值';
comment on column theme_assets.created_at is '创建时间';

comment on table theme_versions is '主题版本表';
comment on column theme_versions.id is '主题版本主键';
comment on column theme_versions.theme_id is '主题配置主键';
comment on column theme_versions.version_no is '版本号';
comment on column theme_versions.snapshot_json is '主题快照 JSON';
comment on column theme_versions.created_by is '创建用户主键';
comment on column theme_versions.created_at is '创建时间';

comment on table tag_aliases is '标签别名表';
comment on column tag_aliases.id is '标签别名主键';
comment on column tag_aliases.tag_id is '标签主键';
comment on column tag_aliases.alias is '别名文本';
comment on column tag_aliases.created_at is '创建时间';

comment on table article_series is '文章系列表';
comment on column article_series.id is '文章系列主键';
comment on column article_series.title is '系列标题';
comment on column article_series.slug is '系列 URL 标识';
comment on column article_series.description is '系列说明';
comment on column article_series.cover_url is '系列封面地址';
comment on column article_series.sort_order is '排序值';
comment on column article_series.status is '系列状态';
comment on column article_series.created_by is '创建用户主键';
comment on column article_series.created_at is '创建时间';
comment on column article_series.updated_at is '更新时间';

comment on table article_series_items is '文章系列条目表';
comment on column article_series_items.series_id is '文章系列主键';
comment on column article_series_items.article_id is '文章主键';
comment on column article_series_items.sort_order is '排序值';
comment on column article_series_items.note is '条目说明';
comment on column article_series_items.created_at is '创建时间';

comment on table article_relations is '相关文章关系表';
comment on column article_relations.id is '相关文章关系主键';
comment on column article_relations.source_article_id is '源文章主键';
comment on column article_relations.target_article_id is '目标文章主键';
comment on column article_relations.relation_type is '关系类型';
comment on column article_relations.sort_order is '排序值';
comment on column article_relations.created_at is '创建时间';

comment on table project_milestones is '作品里程碑表';
comment on column project_milestones.id is '作品里程碑主键';
comment on column project_milestones.project_id is '作品主键';
comment on column project_milestones.title is '里程碑标题';
comment on column project_milestones.description is '里程碑说明';
comment on column project_milestones.milestone_date is '里程碑日期';
comment on column project_milestones.sort_order is '排序值';
comment on column project_milestones.created_at is '创建时间';

comment on table project_links is '作品外链表';
comment on column project_links.id is '作品外链主键';
comment on column project_links.project_id is '作品主键';
comment on column project_links.link_type is '链接类型';
comment on column project_links.label is '展示文本';
comment on column project_links.url is '链接地址';
comment on column project_links.safe_status is '安全校验状态';
comment on column project_links.sort_order is '排序值';
comment on column project_links.created_at is '创建时间';

comment on table project_process_notes is '作品过程记录表';
comment on column project_process_notes.id is '作品过程记录主键';
comment on column project_process_notes.project_id is '作品主键';
comment on column project_process_notes.phase is '过程阶段';
comment on column project_process_notes.title is '过程标题';
comment on column project_process_notes.body is '过程正文';
comment on column project_process_notes.sort_order is '排序值';
comment on column project_process_notes.created_at is '创建时间';
comment on column project_process_notes.updated_at is '更新时间';

comment on table inspiration_sources is '灵感来源表';
comment on column inspiration_sources.id is '灵感来源主键';
comment on column inspiration_sources.inspiration_id is '灵感卡片主键';
comment on column inspiration_sources.source_type is '来源类型';
comment on column inspiration_sources.title is '来源标题';
comment on column inspiration_sources.url is '来源地址';
comment on column inspiration_sources.author is '来源作者';
comment on column inspiration_sources.captured_at is '采集时间';
comment on column inspiration_sources.created_at is '创建时间';

comment on table inspiration_relations is '灵感关联表';
comment on column inspiration_relations.id is '灵感关联主键';
comment on column inspiration_relations.inspiration_id is '灵感卡片主键';
comment on column inspiration_relations.target_type is '关联目标类型';
comment on column inspiration_relations.target_id is '关联目标主键';
comment on column inspiration_relations.relation_type is '关联类型';
comment on column inspiration_relations.created_at is '创建时间';

comment on table content_blocks is '页面内容块表';
comment on column content_blocks.id is '内容块主键';
comment on column content_blocks.owner_type is '归属对象类型';
comment on column content_blocks.owner_id is '归属对象主键';
comment on column content_blocks.block_key is '内容块键';
comment on column content_blocks.block_type is '内容块类型';
comment on column content_blocks.title is '内容块标题';
comment on column content_blocks.body is '内容块正文';
comment on column content_blocks.config_json is '内容块配置 JSON';
comment on column content_blocks.sort_order is '排序值';
comment on column content_blocks.visible is '是否显示';
comment on column content_blocks.created_at is '创建时间';
comment on column content_blocks.updated_at is '更新时间';

comment on table content_block_assets is '内容块资源关联表';
comment on column content_block_assets.block_id is '内容块主键';
comment on column content_block_assets.file_id is '文件资源主键';
comment on column content_block_assets.usage_type is '资源用途类型';
comment on column content_block_assets.sort_order is '排序值';
comment on column content_block_assets.created_at is '创建时间';

comment on table comment_reactions is '评论反应表';
comment on column comment_reactions.id is '评论反应主键';
comment on column comment_reactions.comment_id is '评论主键';
comment on column comment_reactions.user_id is '用户主键';
comment on column comment_reactions.reaction_type is '反应类型';
comment on column comment_reactions.created_at is '创建时间';

comment on table guestbook_entries is '留言板条目表';
comment on column guestbook_entries.id is '留言主键';
comment on column guestbook_entries.user_id is '用户主键';
comment on column guestbook_entries.display_name is '展示名称';
comment on column guestbook_entries.content is '留言内容';
comment on column guestbook_entries.status is '审核状态';
comment on column guestbook_entries.like_count is '点赞数量';
comment on column guestbook_entries.ip_address is '留言 IP 地址';
comment on column guestbook_entries.user_agent is '客户端 User-Agent';
comment on column guestbook_entries.created_at is '创建时间';
comment on column guestbook_entries.updated_at is '更新时间';

comment on table content_statistics is '内容统计聚合表';
comment on column content_statistics.id is '内容统计主键';
comment on column content_statistics.target_type is '统计目标类型';
comment on column content_statistics.target_id is '统计目标主键';
comment on column content_statistics.view_count is '浏览数量';
comment on column content_statistics.like_count is '点赞数量';
comment on column content_statistics.favorite_count is '收藏数量';
comment on column content_statistics.comment_count is '评论数量';
comment on column content_statistics.last_viewed_at is '最后浏览时间';
comment on column content_statistics.updated_at is '更新时间';

comment on table search_logs is '搜索日志表';
comment on column search_logs.id is '搜索日志主键';
comment on column search_logs.keyword is '搜索关键词';
comment on column search_logs.result_count is '结果数量';
comment on column search_logs.user_id is '用户主键';
comment on column search_logs.ip_address is '搜索 IP 地址';
comment on column search_logs.user_agent is '客户端 User-Agent';
comment on column search_logs.created_at is '创建时间';

comment on table daily_metrics is '每日指标聚合表';
comment on column daily_metrics.metric_date is '指标日期';
comment on column daily_metrics.metric_key is '指标键';
comment on column daily_metrics.metric_value is '指标值';
comment on column daily_metrics.detail_json is '指标详情 JSON';
comment on column daily_metrics.created_at is '创建时间';
comment on column daily_metrics.updated_at is '更新时间';

comment on table admin_audit_snapshots is '后台审计快照表';
comment on column admin_audit_snapshots.id is '审计快照主键';
comment on column admin_audit_snapshots.target_type is '快照目标类型';
comment on column admin_audit_snapshots.target_id is '快照目标主键';
comment on column admin_audit_snapshots.snapshot_json is '快照 JSON';
comment on column admin_audit_snapshots.created_by is '创建用户主键';
comment on column admin_audit_snapshots.created_at is '创建时间';

comment on table ai_agent_tasks is 'AI 助手任务表';
comment on column ai_agent_tasks.id is 'AI 任务主键';
comment on column ai_agent_tasks.task_type is '任务类型';
comment on column ai_agent_tasks.target_type is '目标类型';
comment on column ai_agent_tasks.target_id is '目标主键';
comment on column ai_agent_tasks.prompt is '任务提示词';
comment on column ai_agent_tasks.status is '任务状态';
comment on column ai_agent_tasks.provider is '模型供应商';
comment on column ai_agent_tasks.model_name is '模型名称';
comment on column ai_agent_tasks.created_by is '创建用户主键';
comment on column ai_agent_tasks.created_at is '创建时间';
comment on column ai_agent_tasks.updated_at is '更新时间';

comment on table ai_agent_messages is 'AI 助手消息表';
comment on column ai_agent_messages.id is 'AI 消息主键';
comment on column ai_agent_messages.task_id is 'AI 任务主键';
comment on column ai_agent_messages.role is '消息角色';
comment on column ai_agent_messages.content is '消息内容';
comment on column ai_agent_messages.token_count is 'Token 数量';
comment on column ai_agent_messages.created_at is '创建时间';

comment on table ai_suggestions is 'AI 建议表';
comment on column ai_suggestions.id is 'AI 建议主键';
comment on column ai_suggestions.task_id is 'AI 任务主键';
comment on column ai_suggestions.target_type is '建议目标类型';
comment on column ai_suggestions.target_id is '建议目标主键';
comment on column ai_suggestions.suggestion_type is '建议类型';
comment on column ai_suggestions.content is '建议内容';
comment on column ai_suggestions.status is '建议状态';
comment on column ai_suggestions.adopted_by is '采纳用户主键';
comment on column ai_suggestions.adopted_at is '采纳时间';
comment on column ai_suggestions.created_at is '创建时间';

insert into roles (code, name, description)
values
    ('ADMIN', '管理员', '拥有后台 CMS 和站点配置管理权限'),
    ('USER', '注册用户', '可登录、评论、点赞和收藏公开内容')
on conflict (code) do nothing;

do $$
begin
    if '${adminPasswordHash}' !~ '^\$2[aby]\$[0-9]{2}\$.{53}$' then
        raise exception 'ADMIN_PASSWORD_HASH must be a BCrypt hash';
    end if;
end $$;

insert into users (username, nickname, password_hash, status)
values ('${adminUsername}', '管理员', '${adminPasswordHash}', 'ACTIVE')
on conflict (username) do nothing;

insert into user_roles (user_id, role_id)
select u.id, r.id
from users u
join roles r on r.code = 'ADMIN'
where u.username = '${adminUsername}'
on conflict (user_id, role_id) do nothing;

insert into theme_configs (
    theme_name,
    display_name,
    primary_color,
    background_type,
    font_family,
    card_style,
    layout_type,
    is_active,
    config_json
)
values (
    'glass-space',
    'Glass Space',
    '#7c3aed',
    'star',
    'Inter, system-ui, sans-serif',
    'glass',
    'bento',
    true,
    '{"background": "star", "cardStyle": "glass", "layout": "bento"}'::jsonb
)
on conflict (theme_name) do nothing;
