-- 添加登录防暴力破解相关字段
alter table users
    add column if not exists failed_login_attempts int not null default 0,
    add column if not exists account_locked_until timestamptz;

-- 刷新令牌表
create table if not exists refresh_tokens (
    id bigint generated by default as identity primary key,
    user_id bigint not null references users(id) on delete cascade,
    token_hash varchar(64) not null,
    expires_at timestamptz not null,
    created_at timestamptz not null default now(),
    revoked_at timestamptz
);

create index idx_refresh_tokens_token_hash on refresh_tokens(token_hash);
create index idx_refresh_tokens_user_id on refresh_tokens(user_id);
