-- 添加登录防暴力破解相关字段
alter table users
    add column if not exists failed_login_attempts int not null default 0,
    add column if not exists account_locked_until timestamptz;

-- 刷新令牌表
create table if not exists refresh_tokens (
    id bigint generated by default as identity primary key,
    user_id bigint not null references users(id) on delete cascade,
    token_hash varchar(64) not null,
    expires_at timestamptz not null,
    created_at timestamptz not null default now(),
    revoked_at timestamptz
);

create index idx_refresh_tokens_token_hash on refresh_tokens(token_hash);
create index idx_refresh_tokens_user_id on refresh_tokens(user_id);

comment on table refresh_tokens is '刷新令牌表';
comment on column refresh_tokens.id is '主键 ID';
comment on column refresh_tokens.user_id is '用户 ID';
comment on column refresh_tokens.token_hash is '令牌哈希值';
comment on column refresh_tokens.expires_at is '过期时间';
comment on column refresh_tokens.created_at is '创建时间';
comment on column refresh_tokens.revoked_at is '撤销时间';
comment on column users.failed_login_attempts is '连续登录失败次数';
comment on column users.account_locked_until is '账号锁定截至时间';
