-- 用户关注关系表（单向关注）
-- 互相关注即为好友，通过查询交叉关注推导好友关系
create table if not exists user_follows (
    id bigint generated by default as identity primary key,
    follower_id bigint not null references users(id) on delete cascade,
    followee_id bigint not null references users(id) on delete cascade,
    created_at timestamptz not null default now(),
    constraint ck_user_follows_not_self check (follower_id <> followee_id),
    unique (follower_id, followee_id)
);

create index if not exists idx_user_follows_follower on user_follows(follower_id);
create index if not exists idx_user_follows_followee on user_follows(followee_id);

-- 为 users 表补充缺失的字段索引
create index if not exists idx_users_username on users(username);
