-- 用户表增加 email 字段（唯一）
alter table users
    add column if not exists email varchar(320);
alter table users
    add constraint uk_users_email unique (email);

-- 邮件验证码表
create table if not exists email_verification_codes (
    id bigint generated by default as identity primary key,
    email varchar(320)  not null,
    code varchar(6)     not null,
    purpose varchar(20) not null default 'REGISTER',
    created_at timestamptz not null default now(),
    expires_at timestamptz not null,
    used_at timestamptz,
    constraint ck_evc_purpose check (purpose in ('REGISTER', 'RESET_PASSWORD'))
);

create index if not exists idx_evc_email_code on email_verification_codes(email, code);
