-- 通知表：用户通知与管理待审核提醒
create table notifications (
    id          bigint generated by default as identity primary key,
    user_id     bigint not null references users(id) on delete cascade,
    type        varchar(40) not null,
    title       varchar(300) not null,
    content     text,
    target_type varchar(30),
    target_id   bigint,
    actor_id    bigint references users(id) on delete set null,
    actor_name  varchar(120),
    is_read     boolean not null default false,
    created_at  timestamptz not null default now(),
    constraint ck_notifications_type check (type in (
        'COMMENT_ON_ARTICLE', 'REPLY_COMMENT',
        'LIKE_ARTICLE', 'FAVORITE_ARTICLE',
        'LIKE_COMMENT',
        'PENDING_REVIEW'
    ))
);

create index idx_notifications_user_unread on notifications(user_id, is_read, created_at desc);
create index idx_notifications_created on notifications(created_at desc);

comment on table notifications is '用户通知表';
comment on column notifications.user_id is '通知接收用户';
comment on column notifications.type is '通知类型';
comment on column notifications.title is '通知标题';
comment on column notifications.content is '通知正文';
comment on column notifications.target_type is '关联目标类型';
comment on column notifications.target_id is '关联目标主键';
comment on column notifications.actor_id is '触发通知的用户ID';
comment on column notifications.actor_name is '触发通知的用户名';
comment on column notifications.is_read is '是否已读';
comment on column notifications.created_at is '创建时间';
